#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Complete fix for all claude-code-changelog.md translation issues
"""

import re

def complete_changelog_fix():
    """Complete fix for all translation issues"""
    
    with open('final-site/docs/claude-code-changelog.md', 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Start with a complete set of fixes for the entire file
    complete_fixes = {
        # Fix WezTerm spacing issue
        '支持We z Term': '支持 WezTerm',
        
        # Fix spacing in additionalDirectories
        'additiona l Directories': 'additionalDirectories',
        '.claude/设置s.json': '.claude/settings.json',
        
        # Fix broken words throughout
        'can Us e Tool': 'canUseTool',
        'disable Al l Hooks': 'disableAllHooks',
        'syste m Message': 'systemMessage',
        'Sessio n Start': 'SessionStart',
        'Custo m Subagents': 'Custom Subagents',
        'Task Agen t Tools': 'Task Agent Tools',
        'User Prompt Submit': 'UserPromptSubmit',
        'User Promp t Submit': 'UserPromptSubmit',
        'itiona l Context': 'itionalContext',
        'Permissio n Decision': 'PermissionDecision',
        'VSCod e Mac OS': 'VSCode MacOS',
        'aws Refres h Helper': 'awsRefreshHelper',
        'aws Aut h Refresh': 'awsAuthRefresh',
        'aws Credentia l Export': 'awsCredentialExport',
        'Mode l Comparison': 'Model Comparison',
        'Pr e Compact': 'PreCompact',
        'Sto p Hooks': 'Stop Hooks',
        'Subagen t Stop': 'SubagentStop',
        'Typ e Script': 'TypeScript',
        'Release d Python': 'Released Python',
        'CCUsage': 'CC Usage',
        'Claud e Pro': 'Claude Pro',
        'Claud e Max': 'Claude Max',
        'Restartin g Claude Code': 'Restarting Claude Code',
        'Context Windo w Depletion': 'Context Window Depletion',
        'allowed-工具': 'allowed-tools',
        'allowe d Tools': 'allowedTools',
        'ignor e Patterns': 'ignorePatterns',
        'Get tin g Started': 'Getting Started',
        'cleanup Perio d Days': 'cleanupPeriodDays',
        'stee r Claude': 'steer Claude',
        'Claud e Desktop': 'Claude Desktop',
        'CLAUDE.m d Supremacy': 'CLAUDE.md Supremacy',
        'Slas h Commands': 'Slash Commands',
        'Mac-only': '仅限 Mac',
        'mac OS': 'macOS',
        '/approved-工具': '/approved-tools',
        'Accep t Permissions': 'Accept Permissions',
        'Remarkabl e Progress': '非凡的进展',
        'It\\'samazinghowfa r': '令人惊讶的是，',
        'Claude Codehascomeinsucha': 'Claude Code 在如此',
        'shortperiodoftime.': '短时间内取得了如此大的进步。',
        'Fromearlybetaversionstoa': '从早期的测试版本到一个',
        'comprehensivedevelopmentplatformwith': '综合的开发平台，拥有',
        'MCPs,': 'MCP、',
        'auto-permissions,': '自动权限、',
        'planmode,': '计划模式、',
        'real-timesteering,': '实时指导',
        'andsophisticatedworkflows': '和复杂的工作流程',
        'thepaceofinnovationhasbeenextraordinary.': '创新的步伐非常惊人。',
        
        # Fix all concatenated English words and phrases
        'abugin': 'a bug in',
        'wheretheappwouldsometimesfreezeonlaunch': 'where the app would sometimes freeze on launch',
        'progressmessagest o Bash': 'progress messages to Bash',
        'basedonthelast5 linesof': 'based on the last 5 lines of',
        'expandingvariables': 'expanding variables',
        'Movedshellsnapshotsfrom': 'Moved shell snapshots from',
        'formorereliabl e Bash': 'for more reliable Bash',
        'IDEextensionpathhandlingwhe n Claude Coderunsin': 'IDE extension path handling when Claude Code runs in',
        'Redesigne d Search': 'Redesigned Search',
        'withnew': 'with new',
        'parametersandfeatures': 'parameters and features',
        'Disabled IDEdiffsfornotebook': 'Disabled IDE diffs for notebook',
        '修复ing "Timeoutwaitingafter1000ms"': '修复了 "Timeout waiting after 1000ms"',
        'configfilecorruption': 'config file corruption',
        'byenforcingatomicwrites': 'by enforcing atomic writes',
        'prompt': 'prompt',
        'undot o Ctrl': 'undo to Ctrl',
        'toavoidbreakingexistin g Ctrl': 'to avoid breaking existing Ctrl',
        'matchingzsh\\'sundo': 'matching zsh\\'s undo',
        'transcriptpathafter': 'transcript path after',
        'triggeringwhenloopendswith': 'triggering when loop ends with',
        'Restorednamespacingin': 'Restored namespacing in',
        'namesbasedonsubdirectories': 'names based on subdirectories',
        'Forexample': 'For example',
        'resource\\_link': 'resource_link',
        'resultsare': 'results are',
        'annotationsand': 'annotations and',
        'titles': 'titles',
        'displayin': 'display in',
        'mcpview': 'mcp view',
        'Change d Esctoexittranscriptmoderatherthaninterrupt': 'Changed Esc to exit transcript mode rather than interrupt',
        'OAuthusesport45454andproperlyconstructsbrowser': 'OAuth uses port 45454 and properly constructs browser',
        '@-mentionfiletruncationfrom100linesto2000lines': '@-mention file truncation from 100 lines to 2000 lines',
        'fordisabling IDEauto-connection': 'for disabling IDE auto-connection',
        'fornativ e Windows': 'for native Windows',
        'requiresGitfo r Windows': 'requires Git for Windows',
        'fo r Bedrock': 'for Bedrock',
        'throughenvironmentvariable': 'through environment variable',
        'can': 'can',
        'helpyouidentifyand': 'help you identify and',
        'invalid': 'invalid',
        'beusedininteractivemode': 'be used in interactive mode',
        'notjust': 'not just',
        'Increasedauto-compactwarningthresholdfrom60%': 'Increased auto-compact warning threshold from 60%',
        'to80%': 'to 80%',
        'withhandlinguserdirectorieswithspacesforshellsnapshots': 'with handling user directories with spaces for shell snapshots',
        'OTELresource': 'OTEL resource',
        '包括os.type': '包括 os.type',
        'os.version': 'os.version',
        'host.arch': 'host.arch',
        'andwsl.version': 'and wsl.version',
        'ifrunningon Windows Subsystemfo r Linux': 'if running on Windows Subsystem for Linux',
        'user-level': 'user-level',
        'insubdirectories': 'in subdirectories',
        'whererejectedplanfromsub-taskwouldgetdiscarded': 'where rejected plan from sub-task would get discarded',
        'allowspecifyingenvforspawnedprocess': 'allow specifying env for spawned process',
        'exposedpermissiondecisiontohooks': 'exposed permission decision to hooks',
        'includingask': 'including ask',
        'advancedJSONoutput': 'advanced JSON output',
        'claudemcplist': 'claude mcp list',
        'envvarforhook': 'env var for hook',
        'fordisablingIDEauto-connection': 'for disabling IDE auto-connection',
        'runbash': 'run bash',
        'tokens loadedand': 'tokens loaded and',
        'availablefo r Claudetouse': 'available for Claude to use',
        'runmultiplewebqueriesinparallel': 'run multiple web queries in parallel',
        'immediatelyinterrupts Claudei n Auto-acceptmode': 'immediately interrupts Claude in Auto-accept mode',
        'UIglitcheswith': 'UI glitches with',
        'Selectcomponentbehavior': 'Select component behavior',
        'terminal': 'terminal',
        'displaywithbettertexttruncationlogic': 'display with better text truncation logic',
        'Sharedprojectpermissionrulescanbesavedin': 'Shared project permission rules can be saved in',
        'streaming': 'streaming',
        'via': 'via',
        'stream-json': 'stream-json',
        'wherepastingcouldtriggermemoryorbashmodeunexpectedly': 'where pasting could trigger memory or bash mode unexpectedly',
        'wereloadedtwice': 'were loaded twice',
        'whichcaused': 'which caused',
        'callerrors': 'call errors',
        'Navigatemenuswithvim-stylekeys': 'Navigate menus with vim-style keys',
        'orbash/emacs': 'or bash/emacs',
        'forfasterinteraction': 'for faster interaction',
        'Enhancedimagedetectionformorereliableclipboardpastefunctionality': 'Enhanced image detection for more reliable clipboard paste functionality',
        'where ESCkeycouldcrashtheconversationhistoryselector': 'where ESC key could crash the conversation history selector',
        'Copy+pasteimagesdirectlyintoyourprompt': 'Copy+paste images directly into your prompt',
        'progressindicatorsforbashandfetch': 'progress indicators for bash and fetch',
        'Bug': 'Bug',
        'fornon-interactivemode': 'for non-interactive mode',
        't o Memorybystartingyourmessagewith': 'to Memory by starting your message with',
        'toseefull': 'to see full',
        'forlong': 'for long',
        'results': 'results',
        'for MCPSSEtransport': 'for MCP SSE transport',
        'webfetch': 'web fetch',
        'let s Claudeview URLsthatyoupastein': 'lets Claude view URLs that you paste in',
        'abugwith JPEGdetection': 'a bug with JPEG detection',
        'scope': 'scope',
        'youto': 'you to',
        'MCPserversto': 'MCP servers to',
        'andcommitthemtoyourrepository': 'and commit them to your repository',
        'Previous MCPserverscopeshavebeenrenamed': 'Previous MCP server scopes have been renamed',
        'previous': 'previous',
        'scopeis': 'scope is',
        'and': 'and',
        'global': 'global',
        'Pres s Tabtoauto-completefileandfoldernames': 'Press Tab to auto-complete file and folder names',
        'Pres s Shift': 'Press Shift',
        'Tabtotoggleauto-acceptforfileedits': 'Tab to toggle auto-accept for file edits',
        'Automaticconversationcompactionforinfiniteconversationlength': 'Automatic conversation compaction for infinite conversation length',
        'togglewith': 'toggle with',
        'As k Claudetomakea planwiththinkingmode': 'Ask Claude to make a plan with thinking mode',
        'justsay': 'just say',
        'oreven': 'or even',
        'MCPserverstartuptimeoutcan': 'MCP server startup timeout can',
        'beconfiguredvia': 'be configured via',
        'environmentvariable': 'environment variable',
        'MCPserverstartupnolongerblockstheappfromstartingup': 'MCP server startup no longer blocks the app from starting up',
        'letsyouviewreleasenotesatanytime': 'lets you view release notes at any time',
        'claudeconfig': 'claude config',
        'acceptmultiplevaluesseparatedbycommasorspaces': 'accept multiple values separated by commas or spaces',
        'Import MCPserversfrom': 'Import MCP servers from',
        'Desktopwith': 'Desktop with',
        'claude mcp': 'claude mcp',
        '-from-claude-desktop': '-from-claude-desktop',
        'Add MCPserversas JSONstringswith': 'Add MCP servers as JSON strings with',
        '-json': '-json',
        'Vimbindingsfortext': 'Vim bindings for text',
        'with': 'with',
        'or': 'or',
        'Interactive MCPsetupwizard': 'Interactive MCP setup wizard',
        'Run': 'Run',
        'to': 'to',
        'MCPserverswitha': 'MCP servers with a',
        'step-by-stepinterface': 'step-by-step interface',
        'forsome': 'for some',
        'Persisten t Shell': 'Persistent Shell',
        'Customslash': 'Custom slash',
        'Markdown': 'Markdown',
        'in': 'in',
        'directories': 'directories',
        'appearascustomslash': 'appear as custom slash',
        'toinsertpromptsintoyourconversation': 'to insert prompts into your conversation',
        'MCPdebugmode': 'MCP debug mode',
        'Runwith': 'Run with',
        'flagtogetmoreinformationabout': 'flag to get more information about',
        'MCPservererrors': 'MCP server errors',
        'ANSIcolorthemeforbetterterminalcompatibility': 'ANSI color theme for better terminal compatibility',
        'whereslash': 'where slash',
        'argumentsweren\\'tbeingsentproperly': 'arguments weren\\'t being sent properly',
        'APIkeysare': 'API keys are',
        'storedinmac OSKeychain': 'stored in macOS Keychain',
        'formanaging': 'for managing',
        'permissions': 'permissions',
        'Word-leveldiffdisplayfor': 'Word-level diff display for',
        'codereadability': 'code readability',
        'Fuzzymatchingforslash': 'Fuzzy matching for slash',
        
        # Fix remaining English phrases that are scattered throughout
        'adding': '添加',
        'adding了': '添加了',
        'supporting': '支持',
        'supporting支持': '支持',
        'allowing': '允许',
        'allowing允许': '允许',
        'improving': '改进',
        'improving改进': '改进',
        'fixing': '修复',
        'fixing修复': '修复',
        'updating': '更新',
        'updating更新': '更新',
        'enabling': '启用',
        'enabling启用': '启用',
        'disabling': '禁用',
        'disabling禁用': '禁用',
        'removing': '移除',
        'removing移除': '移除',
        
        # Fix common broken patterns
        '工具\_use': 'tool_use',
        '工具\_result': 'tool_result',
        '工具\_decision': 'tool_decision',
        'parent\_工具\_use\_id': 'parent_tool_use_id',
        
        # Fix URL patterns
        'claude-code-输出-styles': 'claude-code-output-styles',
        'claude-code-设置s': 'claude-code-settings',
        'what-are-background-命令': 'what-are-background-commands',
        'what-is-slash-命令-in-claude-code': 'what-is-slash-commands-in-claude-code',
        '额外的-working-directories': 'additional-working-directories',
        
        # Fix date formats
        '9月 11': '9月11日',
        '9月 10': '9月10日', 
        '9月 5': '9月5日',
        '8月 29': '8月29日',
        '8月 28': '8月28日',
        '8月 26': '8月26日',
        '8月 25': '8月25日',
        '8月 22': '8月22日',
        '8月 21': '8月21日',
        '8月 20': '8月20日',
        '8月 19': '8月19日',
        '8月 18': '8月18日',
        '8月 16': '8月16日',
        '8月 14': '8月14日',
        '8月 13': '8月13日',
        '8月 12': '8月12日',
        '8月 8': '8月8日',
        '8月 7': '8月7日',
        '5月 28': '5月28日',
        '5月 22': '5月22日',
        '5月 21': '5月21日',
        '5月 18': '5月18日',
        '5月 13': '5月13日',
        '5月 9': '5月9日',
        '5月 8': '5月8日',
        '5月 5': '5月5日',
        '5月 2': '5月2日',
        '5月 1': '5月1日',
        
        # Fix specific problematic entries that are still mixed
        'We现在emitmessagesfromsub-tasksin': '我们现在在 `-p` 模式下从子任务发出消息',
        'Additional改进and错误修复': '额外的改进和错误修复',
        'lookforthe': '查找',
        'property': '属性',
        'crasheswhenthe VSCodediff': '当 VSCode diff 工具被快速多次调用时的崩溃',
        'isinvokedmultipletimesquickly': '',
        'MCPserverlist UI改进': 'MCP 服务器列表 UI 改进',
        'Updat e Claude Codeprocesstitletodisplay': '更新 Claude Code 进程标题以显示',
        'insteadof': '而不是',
        'can现在alsobeusedwitha': '现在也可以与',
        'subscription': '订阅一起使用',
        'forsmootherswitchingto': '用于平滑切换到',
        'plans': '计划',
        'UIforauthenticationfrom APIkeysan d Bedrock': 'API 密钥和 Bedrock/Vertex/外部身份验证令牌的认证 UI',
        'Vertex/externalauthtokens': '',
        'shellconfiguration错误处理': 'shell 配置错误处理',
        'todolisthandlingduringcompaction': '压缩期间的待办事项列表处理',
        'markdowntable支持': 'Markdown 表格支持',
        'streamingperformance': '流性能',
        'Vertex AIregionfallbackwhenusing': '使用 `CLOUD_ML_REGION` 时的 Vertex AI 区域回退',
        'Increaseddefaultotelintervalfrom1s': '将默认 OTEL 间隔从 1 秒增加到 5 秒',
        'edgecaseswhere': '边缘情况',
        'weren\\'tbeingrespected': '未被遵守',
        'aregressionwheresearch': '搜索工具不必要地请求权限的回归',
        'unnecessarilyaskedforpermissions': '',
        'fortriggeringthinkingnon-Englishlanguages': '支持触发非英语语言的思考',
        'compacting UI': '压缩 UI',
        'Renamed': '重命名',
        'Migrated': '迁移',
        'from': '从',
        'Deprecated': '弃用',
        'infavorofediting': '改为编辑',
        'abugwhere': '一个错误',
        'sometimesdidn\\'tworkin': '有时在',
        'mode': '模式下不工作',
        'editreliabilityfortab-indented': 'tab 缩进文件的编辑可靠性',
        'Respect': '在所有地方尊重',
        'everywhere': '',
        'Reducedunnecessary': '减少了不必要的',
        'permissionprompts': '权限提示',
        'forsymlinksin': '支持符号链接',
        'typeahead': '在预输入中',
        'UIpolish': 'UI 优化',
        'reliability改进': '可靠性改进',
        'errorsweren\\'tbeingparsedcorrectly': '错误未被正确解析',
        'togiveuserstheoptiontooptoutofinterleavedthinking': '为用户提供退出交错思考的选项',
        'modelreferencestoshowprovider-specificnames': '模型引用以显示提供商特定名称',
        'fo r Bedrock': '用于 Bedrock',
        'fo r Console': '用于控制台',
        'documentationlinksand OAuthprocessdescriptions': '文档链接和 OAuth 流程描述',
        'is现在generallyavailable': '现在普遍可用',
        'Introducin g': '引入',
        'an d': '和',
        'models': '模型',
        'Breakingchange': '破坏性变更',
        'Bedrock ARNpassedto': '传递给',
        'shouldnolongercontainanescapedslash': '的 Bedrock ARN 不应再包含转义斜杠',
        'specify': '指定',
        'insteadof': '而不是',
        'infavorof': '改为',
        'tologallrequests': '记录所有请求',
        'JSON': 'JSON',
        'returnsnestedmessageobjects': '返回嵌套消息对象',
        'forforwards-compatibilityasweintroducenewmetadatafields': '为前向兼容性，因为我们引入了新的元数据字段',
        'envvar': '环境变量',
        'sendmessagesto Claudewhileitworkstostee r': '在 Claude 工作时向其发送消息以进行',
        'Claudeinreal-time': '实时指导',
        'envvars': '环境变量',
        'abugwherethinkingwasnotworkingin': '思考在 `-p` 模式下不工作的错误',
        'aregressionin': '回归',
        'reporting': '报告',
        'Deprecated MCPwizardinterfaceinfavorofother': '弃用 MCP 向导界面，改用其他',
        'Lotsofotherbug': '大量其他错误',
        'and改进': '和改进',
        'can现在importother': '现在可以导入其他',
        'Add': '添加',
        'toload': '以在启动时加载',
        'onlaunch': '额外文件',
        'MCPSSEserverconfigscan现在specifycustomheaders': 'MCP SSE 服务器配置现在可以指定自定义标头',
        'abugwhere MCPpermissionpromptdidn\\'talwaysshowcorrectly': 'MCP 权限提示并不总是正确显示的错误',
        'can现在searchtheweb': '现在可以搜索网络',
        'Movedsystem': '将系统',
        'accountstatusto': '和账户状态移至',
        'wordmovementkeybindingsfo r Vim': 'Vim 的单词移动键绑定',
        'latencyforstartup': '启动延迟',
        'andfileedits': '和文件编辑',
        'thinkingtriggeringreliability': '思考触发可靠性',
        'reliabilityforimagesandfolders': '图像和文件夹的可靠性',
        'can现在pastemultiplelargechunksintooneprompt': '现在可以将多个大块粘贴到一个提示中',
        'acrashcausedbya stackoverflowerror': '由堆栈溢出错误引起的崩溃',
        'Madedbstorageoptional': '使数据库存储可选',
        'missingdb': '缺少数据库',
        'disables': '禁用',
        'an问题whereauto-compactwasrunningtwice': '自动压缩运行两次的问题',
        'can现在alsobeusedwitha': '现在也可以与 Claude Max 订阅一起使用',
        'Resumeconversationsfromwhereyouleftofffromwith': '使用 `claude --continue` 和 `claude --resume` 从您停止的地方恢复对话',
        '现在hasaccesstoa Todolistthathelpsitstayontrackandbemoreorganized': '现在可以访问待办事项列表，帮助其保持跟踪并更有组织',
        'for': '支持',
        'Renamed': '重命名',
        'forconsistency': '以保持一致性',
        'etc.': '等',
        'Hit Entertoqueueup': '按 Enter 键排队',
        'messageswhil e Claudeisworking': '消息，而 Claude 正在工作',
        'Draginorcopy/pasteimage': '拖入或复制/粘贴图像',
        'directlyintotheprompt': '直接到提示中',
        'todirectly': '直接',
        'themtocontext': '将它们添加到上下文',
        'Runone-off MCPserverswith': '使用 `claude --mcp-config <path-to-file>` 运行一次性 MCP 服务器',
        'performanceforfilenameauto-complete': '文件名自动完成的性能',
        'Additionalupdatesand': '额外的更新和',
        'forrefreshingdynamicallygenerated APIkeys': '支持刷新动态生成的 API 密钥',
        'via': '通过',
        'witha': '具有',
        'minute TTL': '分钟 TTL',
        'can现在performwritesandrunbash': '现在可以执行写入和运行 bash',
        'spinnertoindicatetokensloadedand': '旋转器以指示加载的令牌和',
        'usage': '使用情况',
        'like': '如',
        'are现在available': '现在可供',
        'touse': '使用',
        'can现在runmultiplewebqueriesinparallel': '现在可以并行运行多个网络查询',
        'Pressing ESConceimmediatelyinterrupts': '按 ESC 一次立即中断',
        'i n Auto-acceptmode': '在自动接受模式下的 Claude',
        'UIglitcheswith': 'UI 故障和',
        'Selectcomponentbehavior': 'Select 组件行为',
        'Enhancedterminal': '增强的终端',
        'displaywithbettertexttruncationlogic': '显示，具有更好的文本截断逻辑'
    }
    
    # Apply complete fixes
    for en_text, zh_text in complete_fixes.items():
        content = content.replace(en_text, zh_text)
    
    # Pattern-based cleanup for remaining issues
    # Fix concatenated words that are still broken
    content = re.sub(r'([a-z])([A-Z])', r'\1 \2', content)
    
    # Fix specific patterns that cause issues
    content = re.sub(r'can现在', '现在可以', content)
    content = re.sub(r'are现在', '现在', content)
    content = re.sub(r'is现在', '现在', content)
    content = re.sub(r'现在supported', '现在支持', content)
    content = re.sub(r'现在be', '现在', content)
    content = re.sub(r'now现在', '现在', content)
    
    # Fix remaining English words mixed with Chinese
    content = re.sub(r'([a-zA-Z]+)现在([a-zA-Z]+)', r'\1 现在 \2', content)
    content = re.sub(r'([a-zA-Z]+)and([a-zA-Z]+)', r'\1 and \2', content)
    content = re.sub(r'([a-zA-Z]+)for([a-zA-Z]+)', r'\1 for \2', content)
    content = re.sub(r'([a-zA-Z]+)with([a-zA-Z]+)', r'\1 with \2', content)
    content = re.sub(r'([a-zA-Z]+)to([a-zA-Z]+)', r'\1 to \2', content)
    content = re.sub(r'([a-zA-Z]+)in([a-zA-Z]+)', r'\1 in \2', content)
    content = re.sub(r'([a-zA-Z]+)of([a-zA-Z]+)', r'\1 of \2', content)
    
    # Write the fixed content back
    with open('final-site/docs/claude-code-changelog.md', 'w', encoding='utf-8') as f:
        f.write(content)
    
    print("✅ Complete changelog translation fix applied")
    print("📄 File saved: final-site/docs/claude-code-changelog.md")

if __name__ == "__main__":
    complete_changelog_fix()